id: 4e9dedb8f1f44ecc8e814fd8ad3fee45
initial_creation_type: ocr
source_metadata:
  volumes:
    ce5d323de6834aff976650f9f9b009de:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: ''
      total_pages: 1484
      volume_number: 93
